import glob
import os
import pickle
import shutil
from pathlib import Path


def fileToList(f):
    out = open(f, "r").readlines()
    out = [x.strip() for x in out]
    out = [x for x in out if len(x)]
    return out


filter_list = set(fileToList("splits/ignore_list.txt"))
train_list = set(fileToList("splits/crossmodal_train.txt"))
test_list = set(fileToList("splits/crossmodal_test.txt"))


def split_data(dataset_path):
    # train - test split (original solo mode)
    for split_list, split_name in zip([train_list, test_list], ["train", "test"]):
        Path(f"{split_name}/motions").mkdir(parents=True, exist_ok=True)
        Path(f"{split_name}/wavs").mkdir(parents=True, exist_ok=True)
        for sequence in split_list:
            if sequence in filter_list:
                continue
            motion = f"{dataset_path}/motions/{sequence}.pkl"
            wav = f"{dataset_path}/wavs/{sequence}.wav"
            assert os.path.isfile(motion)
            assert os.path.isfile(wav)
            motion_data = pickle.load(open(motion, "rb"))
            trans = motion_data["smpl_trans"]
            pose = motion_data["smpl_poses"]
            scale = motion_data["smpl_scaling"]
            out_data = {"pos": trans, "q": pose, "scale": scale}
            pickle.dump(out_data, open(f"{split_name}/motions/{sequence}.pkl", "wb"))
            shutil.copyfile(wav, f"{split_name}/wavs/{sequence}.wav")


def split_data_duet(dataset_path):
    """Three-way train/val/test split for the duet task.

    Reads duet_train.txt, duet_val.txt, duet_test.txt from splits/.
    All splits are disjoint at the music_id level — no data leakage across
    sequences from the same song.  Generated by data/create_duet_splits.py.
    """
    duet_train = set(fileToList("splits/duet_train.txt"))
    duet_val   = set(fileToList("splits/duet_val.txt"))
    duet_test  = set(fileToList("splits/duet_test.txt"))

    for split_list, split_name in zip(
        [duet_train, duet_val, duet_test], ["train", "val", "test"]
    ):
        Path(f"{split_name}/motions").mkdir(parents=True, exist_ok=True)
        Path(f"{split_name}/wavs").mkdir(parents=True, exist_ok=True)
        copied = 0
        for sequence in sorted(split_list):
            if sequence in filter_list:
                continue
            motion = f"{dataset_path}/motions/{sequence}.pkl"
            wav = f"{dataset_path}/wavs/{sequence}.wav"
            if not os.path.isfile(motion) or not os.path.isfile(wav):
                print(f"  [SKIP] missing: {sequence}")
                continue
            motion_data = pickle.load(open(motion, "rb"))
            out_data = {
                "pos":   motion_data["smpl_trans"],
                "q":     motion_data["smpl_poses"],
                "scale": motion_data["smpl_scaling"],
            }
            pickle.dump(out_data, open(f"{split_name}/motions/{sequence}.pkl", "wb"))
            shutil.copyfile(wav, f"{split_name}/wavs/{sequence}.wav")
            copied += 1
        print(f"  {split_name}: {copied} sequences copied")
